version: '3'
services:
  java_mysql:
    image: mysql:5.7.22
    command: ['mysqld', '--ssl=0', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    container_name: java_mysql
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_USER: java
      MYSQL_DATABASE: java
      MYSQL_USER_HOST: '%'
      MYSQL_PASSWORD: java
      MYSQL_ROOT_PASSWORD: java
